---
title: "interpolation total"
author: "Jessica French"
date: "`r Sys.Date()`"
output: html_document
---
## Purpose

This markdown will interpolate across our whole AOI using IDW (inverse distance weighting). A separate interpolation will be run for each season. 

## Set up
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r label = "read in packages"}
library(tidyverse)
library(tmap)
library(terra)
library(sf)
library(gstat)
```

```{r label = "set data directory"}
# set data directory to intermediate data folder on tsosie
datadir <- "/capstone/kelpgeomod/intermediate_data/"
```

```{r label = "read in nutrient file"}
# Read in the combined nutrient file
nutrients <- readRDS(file.path(datadir, "/joined_nutrients/joined_nutrients.RDS"))

# read in mask
mask <- rast("/capstone/kelpgeomod/intermediate_data/mask/mask_rast.tif")
```

## Phosphate interpolation

```{r label = "source in function"}
# source in function that creates a list of data frames by quarter
source("~/capstone/Interpolation/idw_prep.R")
```

```{r label = "phosphate quarters"}
# no need to assign this to anything, assignment is done in the function. 
idw_prep_quarters("phosphate", nutrients)

idw_prep_year_quarters("phosphate", nutrients)

# creates phosphate_quarter_df_list object
```


```{r label = "create phosphate raster and remove geom"}
# Would repeat this for each nutrient. 
phosphate_rast_list <- list()
count <- 1
for (i in seq_along(phosphate_quarter_df_list)) {
  # convert dataframe to SpatVect
  vect_i <- terra::vect(phosphate_quarter_df_list[[i]])
  # Rasterize using the mask. 
  rast <- terra::rasterize(vect_i, mask, field = "phosphate")
  # assign to index in phosphate_rast_list
  phosphate_rast_list[[i]] <- rast
}

#plot(phosphate_rast_list[[1]])

# Also repeat this for each nutrient
phosphate_no_geom_list <- list()

# gstat does not play nice with sf so this removes the geometry column. 
for (i in seq_along(phosphate_quarter_df_list)) {
  df <- as.data.frame(phosphate_quarter_df_list[[i]]) |> 
    dplyr::select(-geometry)
  
  phosphate_no_geom_list[[i]] <- df
}
 
```

## Try the above for year and quarter

```{r label = "year and quarter convert to raster"}
# repeat the above code chunk for the year and quarter data (36 elements)
# need to add a line that checks if the rasters are empty.
# Would repeat this for each nutrient. 
test <- phosphate_year_quarter_df_list[[25]] 

all(is.na(test$phosphate))

phosphate_rast_list <- list()
# count <- 1
for (i in seq_along(phosphate_year_quarter_df_list)) {
  df <- phosphate_year_quarter_df_list[[i]]
  # Check if there are only na values (this if statement is not doing anything)
  if (all(is.na(df$phosphate))) {
    message(paste("The spatial data frame at index", i, "is empty"))
    
  } else {
    
  # convert dataframe to SpatVect
  vect_i <- terra::vect(df)
  # Rasterize using the mask. 
  rast <- terra::rasterize(vect_i, mask, field = "phosphate")
  # assign to index in phosphate_rast_list
  phosphate_rast_list[[i]] <- rast
  
  }
}

plot(phosphate_rast_list[[36]])

# Also repeat this for each nutrient
phosphate_no_geom_list <- list()

# gstat does not play nice with sf so this removes the geometry column. 
for (i in seq_along(phosphate_year_quarter_df_list)) {
  df <- as.data.frame(phosphate_year_quarter_df_list[[i]]) |> 
    select(-geometry)
  
  phosphate_no_geom_list[[i]] <- df
}
```


```{r label = "phosphate IDW"}

phosphate_formula_list <- list()
# loop to define formula
for (i in seq_along(phosphate_no_geom_list)) {
  #formula_name <- paste0("phosphate_form_", i)
  formula <- gstat(formula = phosphate~1,
        locations = ~x+y, 
        data = phosphate_no_geom_list[[i]], 
        nmax = Inf, 
        set = list(idp = 4))
  
  phosphate_formula_list[[i]] <- formula
}


# # Define formula
# gs <- gstat(formula=phosphate~1, 
#             locations=~x+y, 
#             data=phosphate_no_geom_list[[3]], 
#             nmax=Inf, 
#             set=list(idp=4)) # 4 is a litle arbitrary at this point. 



phosphate_interpolate_list <- list()
# loop to interpolate
for (i in seq_along(phosphate_formula_list)) {
  interpolation <- interpolate(phosphate_rast_list[[i]], phosphate_formula_list[[i]], debug.level = 0) |> 
    mask(mask)
  
  phosphate_interpolate_list[[i]] <- interpolation
}

# use terra::interpolate to fill in values in blank raster
# idw <- interpolate(phosphate_rast_list[[3]], gs, debug.level=0)



# apply mask 
# idwr <- mask(idw, mask)
# plot(idwr, 1)

plot(phosphate_interpolate_list[[]], 1)
```

```{r}
write_rds(phosphate_interpolate_list, "/capstone/kelpgeomod/analysis_data/inteprolate_1/phosphate_quarterly.RDS")
```

