---
title: "Untitled"
author: "Jessica French"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r label = "set up", include=FALSE, echo=FALSE}
library(sp)
library(terra)
library(cartography)
library(mapsf)
library(ggpattern)
library(RColorBrewer)

datadir <- "/capstone/kelpgeomod/new_file_structure"
```

# Introduction

This markdown document reads in the output of maxent species distribution modelling conducted in Wallace and the usgs_substrate.shp file to show how the estimates of giant kelp habitat suitability compare to substrate distribution. 

```{r label = "read in data"}
# read in the usgs_substrate.shp file 
substrate <- st_read(file.path(datadir, "/02-intermediate-data/substrate/usgs_substrate_shape/usgs_substrate.shp"))

land <- st_read(file.path(datadir, "/01-raw-data/land_bounds/California_County_Boundaries/cnty19_1.shp")) |> 
  mutate(OBJECTID = as.numeric(OBJECTID))

# read in maxent output as tif files. In the current iteration of this project there are four tif files, one for each quarter. 

maxent_q1 <- rast(file.path(datadir, "03-analysis-data/maxent/quarter_1/results/Macrocystis_pyrifera_cloglog.tif"))
```

```{r}
# define points for the 
x_min <- -120.6
x_max <- -119.25
y_min <- 34.15
y_max <- 34.56

# Create a matrix of the bounding box coordinates
bbox_matrix <- matrix(c(x_min, x_max, x_max, x_min, x_min,
                        y_min, y_min, y_max, y_max, y_min), ncol = 2, byrow = TRUE)

# Create a polygon object
bbox_polygon <- st_polygon(list(bbox_matrix))

# filter the substrate shape file to only the soft bottom areas
substrate_filter <- substrate |> 
  filter(class == "s") |> 
  st_make_valid() |> 
  st_filter(bbox)


plot(substrate_filter$geometry)
```

# Mapping

## Quarter 1



```{r label = "map q1"}
# define the palette
color_palette <- brewer.pal(n = 6, name = "Greens")
# initial plot
plot(land$geometry, xlim = c(-120.6, -119.25), 
     ylim = c(34.15, 34.56))




plot(land$geometry, col = "#DFA632", xlim = bbox[1, ], ylim = bbox[2, ])

plot(maxent_q1, col = color_palette, 
     xlim = c(-120.6, -119.25), 
     ylim = c(34.15, 34.56), 
     add = TRUE) # set custom extent to focus on the area with both maxent output and substrate values. 

hatched_feature <- hatchedLayer(
  x = substrate_filter,
  pattern = "diamond",
  density = 9,
  lwd = 0.3,
  add = TRUE)

legendHatched(pos = "topright",
              title.txt = "",
              categ = "",
              patterns = "diamond",
              density = 9,
              col = "black",
              ptrn.bg = "white")

layoutLayer(title = "Giant Kelp Habitat Suitability and Soft Substrate",
            frame = T)

```

