---
title: "calCOFI"
author: "Elke Windschitl"
date: "2023-03-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sf)
library(tmap)
```

```{r}
# Read in AOI
aoi <- st_read("/capstone/kelpgeomod/raw_data/New_AOI_SBchannel_shp/New_AOI_SBchannel.shp")

# Read in CalCOFI cast data
CalCOFI_cast <- read_csv("/capstone/kelpgeomod/raw_data/CalCOFI/Cast.csv") %>% 
  filter(Year >= 2014) %>% 
  dplyr::select(c("Cst_Cnt", "Quarter", "Year", "Lat_Dec", "Lon_Dec"))

# Read in the CalCOFI bottle data
CalCOFI_bottle <- read_csv("/capstone/kelpgeomod/raw_data/CalCOFI/Bottle.csv", locale = locale(encoding = "latin1"))

# Join cast and bottle data
CalCOFI_join <- CalCOFI_bottle %>% 
  right_join(CalCOFI_cast, by = "Cst_Cnt") %>% 
  dplyr::select(c("Lon_Dec", "Lat_Dec", "Depthm", "T_degC", "Quarter", "Year","PO4uM", "NO2uM", "NO3uM", "NH3uM")) %>% 
  filter(Depthm <= 10) %>% 
  st_as_sf(coords = c(lon = "Lon_Dec", lat = "Lat_Dec"), crs = "EPSG: 4326") %>% 
  st_filter(aoi) %>% 
  relocate("geometry", .after = "Year") %>% 
  relocate("NO3uM", .after = "geometry") %>% 
  relocate("NO2uM", .after = "NO3uM") %>% 
  relocate("NH3uM", .after = "NO2uM") %>% 
  set_names(c("depth", "temp", "quarter", "year", "geometry", "nitrate", "nitrite", "ammonia", "phosphate"))
```

```{r}
CalCOFI_ave <- CalCOFI_join %>% 
  group_by(quarter, year, geometry) %>% 
  summarise(temp = mean(temp, na.rm = TRUE),
            nitrate = mean(nitrate, na.rm = TRUE),
            nitrite = mean(nitrite, na.rm = TRUE),
            ammonia = mean(ammonia, na.rm = TRUE),
            phosphate = mean(phosphate, na.rm = TRUE)) %>% 
  mutate("source" = "CalCOFI")

tm_shape(CalCOFI_ave) +
  tm_dots()
```

```{r}
write_rds(x = CalCOFI_ave, file = "/capstone/kelpgeomod/intermediate_data/calcofi/calcofi_nutrients.RDS")
```

```{r}
# # Split full data frame by each year
# split_by_year <- split(x = CalCOFI_join, f = as.factor(CalCOFI_join$Year))
# 
# # Create an empty list to store the results
# df_list <- list()
# 
# # Split each of those years into quarters and store in df_list
# for (i in names(split_by_year)) {
#   split_by_quarter <- split(x = split_by_year[[i]], f = as.factor(split_by_year[[i]]$Quarter))
#   for (j in names(split_by_quarter)) {
#     df_list[[paste0("calCOFI_", i, "_", j)]] <- split_by_quarter[[j]]
#   }
# }
# ```
# 
# ```{r}
# # Create a temporary directory to save the RDS files
# temp_dir <- tempdir()
# for (i in seq_along(df_list)) {
#   file_name <- paste0(names(df_list[i]), ".rds")
#   saveRDS(file = file.path(temp_dir, file_name), df_list[[i]])
# }
# 
# # Use the zip() function to create a compressed ZIP file
# zip("/capstone/kelpgeomod/intermediate_data/calcofi/calcofi_nutrients.zip", files = list.files(temp_dir, full.names = TRUE))
# 
# # Remove the temporary directory
# unlink(temp_dir, recursive = TRUE)

```

