---
title: "Kelp LTER Bottle Data Wrangling"
author: "Erika Egg"
date: '`r format(Sys.time(), "%m/%d/%Y")`'
output: html_document
---

```{r}
# Load in packages
library(tidyverse)
library(janitor)
library(sf)
library(tmap)
library(lubridate)
```


```{r}
# Read in the file of verified sites. Data link: https://sbclter.msi.ucsb.edu/data/catalog/package/?package=knb-lter-sbc.10
#lter_bottle_data <- read_csv2("~/Desktop/meds/capstone/data/LTER_bottle/LTER_monthly_bottledata_20220930.txt")
lter_bottle_data <- read.table("~/Desktop/meds/capstone/data/LTER_bottle/LTER_monthly_bottledata_20220930.txt", sep = ";", header = TRUE)
#lter_bottle_data <- read_csv2("/capstone/kelpgeomod/raw_data/LTER_bottle/LTER_monthly_bottledata_20220930.txt")
```

```{r}
# Need to fix the lat and lon column, they are not separated with decimal or anything, from the website they are in decimal degrees. Lat is two digits before the decimal and lon is three. 
data_cleaned <- lter_bottle_data %>% 
  clean_names() #%>% 
  #filter(longitude_e < 0) # grabs lons with proper format

#stringi::stri_sub(data_cleaned$latitude_n, 3, 2) <- '.' 
#stringi::stri_sub(data_cleaned$longitude_e, 5, 4) <- '.'

data_selected <- data_cleaned %>%
  mutate("latitude_n" = as.numeric(latitude_n),
         "longitude_e" = as.numeric(longitude_e),
         "yyyy_mm_dd" = as.Date(yyyy_mm_dd)) %>%
  dplyr::select(date = yyyy_mm_dd, lon = longitude_e, lat = latitude_n, depth = target_depth_m, phosphate = po4_umol_l, nitrate_nitrite = no2_no3_umol_l, ammonium = ammonia_umol_l, temp = ta_pco2_temperature_deg_c)

# Get month dates to just be first of month
data_selected$date <- floor_date(data_selected$date, unit = "month")

# We also want to set what our latitude and longitude bounds of our area of interest are.
lower_lat <- 33.85
upper_lat <- 34.59
lower_lon <- -120.65
upper_lon <- -118.80

# Filter to relevant time period and AOI, creating quarter and year columns and standardizing missing values
data_2014_2022 <- data_selected %>%
  filter(year(date) >= 2014) %>% # get data for our time period of interest
  mutate(quarter = quarter(date),
         year = year(date)) %>% # get year and quarter columns from the date
  mutate_at(vars(phosphate, nitrate_nitrite, ammonium, temp), ~ifelse(. %in% "99999", NA, .)) %>% # change 99999 missing value code to NA
  mutate_at(vars(phosphate, nitrate_nitrite, ammonium), ~ifelse(. %in% "BDL", 0, .)) %>% # change BDL missing value code to 0
  mutate(phosphate = as.numeric(phosphate),
         nitrate_nitrite = as.numeric(nitrate_nitrite),
         ammonium = as.numeric(ammonium)) %>% # ensure they are numeric for later means
  filter(lat >= lower_lat & lat <= upper_lat & lon >= lower_lon & lon <= upper_lon) # filter to our area of interest

# Summarize data by quarter
data_summarized <- data_2014_2022 %>%
  group_by(lat, lon, year, quarter, temp) %>% # add depth here if want to keep depth as a dividing factor
  summarize(phosphate = mean(phosphate, na.rm = TRUE),
            nitrate_nitrite = mean(nitrate_nitrite, na.rm = TRUE),
            ammonium = mean(ammonium, na.rm = TRUE)) # take quarterly means of monthly data

data_summarized['source'] = 'lter_bottle' # add a source column for tracking when combining with other nutrient data

# Save the csv
write.csv(data_summarized, file = "~/Desktop/meds/capstone/data/LTER_bottle/lter_bottle_new_coords_2014_2022.csv", row.names = FALSE)
saveRDS(data_summarized, "~/Desktop/meds/capstone/data/LTER_bottle/lter_bottle_new_coords_2014_2022.RDS")
```


```{r}
# Read in csv
lter_bottle_data_standardized <- read_csv("~/Desktop/meds/capstone/data/LTER_bottle/lter_bottle_new_coords_2014_2022.csv")
#lter_bottle_data_standardized <- read_csv("/capstone/kelpgeomod/intermediate_data/lter_bottle_nutrients/lter_bottle_new_coords_2014_2022.csv")

######
# not needed for now: may need when converting to rasterStack. otherwise can delete
#lter_bottle_data_standardized$date <- as.Date(paste0(lter_bottle_data_standardized$year, "-", as.character((lter_bottle_data_standardized$quarter-1)*3+1), "-01"))

#lter_bottle_data_standardized_for_sf <- lter_bottle_data_standardized %>%
  #dplyr::select(-year, -quarter, -...1)
######

# Convert the lat and lon columns to point geometry
data_sf <- lter_bottle_data_standardized %>% 
  st_as_sf(coords = c("lon", "lat"), 
           crs = 4326) 
```

```{r}
# Load the mask
mask <- raster::raster("~/Desktop/meds/capstone/Data-Cleaning/mask/mask_rast.tif")
#mask <- raster::raster("/capstone/kelpgeomod/intermediate_data/mask/mask_rast.tif")

# Make sure the sf data has the same CRS as the mask
sf_data_2 <- st_transform(data_sf, crs = raster::projection(mask))


# Crop the sf data to the extent of the mask
data_2_crop <- st_crop(sf_data_2, mask)

# Write spatial csv
write.csv(data_2_crop, file = "~/Desktop/meds/capstone/data/LTER_bottle/lter_bottle_new_coords_2014_2022_geom.csv")
saveRDS(data_2_crop, "~/Desktop/meds/capstone/data/LTER_bottle/lter_bottle_new_coords_2014_2022_geom.RDS")
```

